###
GET http://localhost:1234/projects

###
POST  http://localhost:1234/projects
Content-Type: application/json

{
 "name": "Aplicación de Organización",
 "color": "#e1e1e1",
 "userId": "usuario_1"
}

###
POST http://localhost:1234/tareas
content-type: application/json
  
{
  "title": "Comprar Lija para el Drill", 
  "type": "todo", 
  "urgency": "pending"
}

###
GET http://localhost:1234/tareas/todo?urgency=today

###
PATCH http://localhost:1234/tareas/69617c859c8ff3cd139e612b
Content-Type: application/json

{
  "urgency": "done"
}

###
POST http://localhost:1234/tareas
content-type: application/json

{
  "title": "Vista de Día", 
  "type": "task", 
  "projectId": "69654d389c8ff3cd139e6130",
  "status": "in_progress",
  "workSessions": [
    {
      "start": "2026-01-12T12:30Z",
      "end": "2026-01-12T15:00Z"
    }
  ]
}



###
POST http://localhost:1234/tareas
content-type: application/json

{
  "title": "Concierto Forasteros", 
  "type": "appointment", 
  "start": "2026-01-18T17:00Z",
  "end": "2026-01-18T22:00Z",
  "location": "American Trade"
}

###
POST http://localhost:1234/tareas
content-type: application/json

{
  "title": "Ensayo Sinfónica", 
  "type": "recurrent", 
  "slots":[
    {
      "day": "lunes",
      "startTime": "07:30",
      "endTime": "10;30"
    },
        {
      "day": "martes",
      "startTime": "07:30",
      "endTime": "10;30"
    },
        {
      "day": "miercoles",
      "startTime": "07:30",
      "endTime": "10;30"
    },
        {
      "day": "jueves",
      "startTime": "07:30",
      "endTime": "10;30"
    },
        {
      "day": "viernes",
      "startTime": "07:30",
      "endTime": "10;30"
    }
  ]
}

###
PATCH http://localhost:1234/tareas/695b5d0d04de833f1e261986
Content-Type: application/json

{
  "title": "Hacer buenos títulos para el video de como hacer una campaña"
} 

###
POST http://localhost:1234/tareas
content-type: application/json

{
  "title": "locura", 
  "type": "todo", 
  "projectId": "695c0b3f91f4fcb3581fe6ec",
  "status": "done"
}

###
GET http://localhost:1234/tareas/day?date=2026-01-12